### PR TITLE
Add Tracks to handle EncodedFrame data

### PR DESCRIPTION
**Pull request by at-wat**

### CODE REVIEW

**Comment by at-wat** [comment]
@Sean-Der Added a pseudo code of play-from-disk example. What do you think?

**Comment by Sean-Der** [comment]
This is fantastic! Thank you so much, I feel really good about that.

**Comment by Sean-Der** [comment]
I would merge and we can push on ahead. My last two questions were 

* implementing a 'fan out'. How could I implement a SFU, basically the broadcast example we have right now.
* Handling codec decisions at run-time. This has to be available to both offerer/answerer. I like your idea of using WebRTC APIs, not exactly sure how it works yet though.

**Comment by at-wat** [comment]
> - implementing a 'fan out'. How could I implement a SFU, basically the broadcast example we have right now.

It should be done by a combination of single `TrackRemoteRTP` and multiple `TrackLocalRTP`s. Just write a RTP Packet read from the remote track to the local tracks.

> - Handling codec decisions at run-time. This has to be available to both offerer/answerer. I like your idea of using WebRTC APIs, not exactly sure how it works yet though.

I believe it should be done in `Track.SetParameters()` and `Track.Parameters()`.
Answerer's RTPSender/Receiver gets offerer's codecs by `SetParameters()` called by `PeerConnection` and returns available codecs and selected codecs by `Parameters()`

I just noticed that comment of `staticLocalRTPTrack.SetParameters()` is misreading.
https://github.com/pion/webrtc-v3-design/blob/2e0f9748bf9ed81915a967a79b1654675e380559/webrtc/pkg/media/track.go#L20-L21
It's not for asserting but for selecting a codec from available local codecs and requested other peer's codecs.

**Pull request merged**
